{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "88648ef3_004571d0",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 5
      },
      "lineNbr": 0,
      "author": {
        "id": 1000056
      },
      "writtenOn": "2023-02-10T11:41:11Z",
      "side": 1,
      "message": "The failures in CI are not related to this patch\n",
      "revId": "01cf14dd41cae9c68cb5e76a815747a0d2a19a4a",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda"
    }
  ]
}