{
  "comments": [
    {
      "key": {
        "uuid": "0998aae9_e86663b5",
        "filename": "tools/fiptool/fiptool.c",
        "patchSetId": 1
      },
      "lineNbr": 757,
      "author": {
        "id": 1000043
      },
      "writtenOn": "2020-06-30T07:33:58Z",
      "side": 1,
      "message": "I don\u0027t fully agree with this change and similar ones. I agree that\n\n fiptool help create\n\nshould return 0, which is not the case today. However,\n\n fiptool create\n\nshould continue to fail (because of an invalid number of arguments) and exit 1.\n\nThe trouble is that create_usage() is called in both contexts. I suspect we need to refactor the code a bit to fix this behaviour. Probably create_usage() should not exit and should let its caller take care of it.",
      "range": {
        "startLine": 757,
        "startChar": 1,
        "endLine": 757,
        "endChar": 32
      },
      "revId": "1adc74f2f5a869226618cabd456dcc1e9a6e2a63",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda",
      "unresolved": true
    }
  ]
}