{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "387ed242_7866039b",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1000043
      },
      "writtenOn": "2023-01-05T13:23:26Z",
      "side": 1,
      "message": "I am advised the CI failure might go away if the patch gets rebased on latest integration.",
      "revId": "23db2d9c31dff37c7b7808ed7d73f77879966e76",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda"
    }
  ]
}