{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "440bf849_cb941000",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1000328
      },
      "writtenOn": "2022-02-07T08:40:03Z",
      "side": 1,
      "message": "I saw few CI failures, I believe these failures are not related to this patch, but please confirm.",
      "revId": "341ec12dec4bf15b87d9ca43a266703192b05f06",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "6817cb32_0be4c2dc",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1000715
      },
      "writtenOn": "2022-02-07T09:40:30Z",
      "side": 1,
      "message": "They don\u0027t seem related, but I can\u0027t run CI myself, could you re-run on the new patch?",
      "parentUuid": "440bf849_cb941000",
      "revId": "341ec12dec4bf15b87d9ca43a266703192b05f06",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda"
    }
  ]
}