{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "36e5f083_39d4e589",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1000695
      },
      "writtenOn": "2021-10-04T18:46:56Z",
      "side": 1,
      "message": "I noticed that the uart0_3 and uart0_4 tests failed. Is this expected? If not, is there a way we can run these tests on our end?",
      "revId": "4df617870caffe4fa1f08336b8c6fd929e381366",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda"
    }
  ]
}