{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "75a496c8_418d8d0e",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 6
      },
      "lineNbr": 0,
      "author": {
        "id": 1000043
      },
      "writtenOn": "2023-09-25T08:47:05Z",
      "side": 1,
      "message": "The CI test which was previously failing should be fixed now, thus I am triggering a new CI session against these patches.",
      "revId": "616b3ce27d9a8a83a189a16ff6a05698bc6df3c8",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "27391e29_9a90f35c",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 6
      },
      "lineNbr": 0,
      "author": {
        "id": 1000043
      },
      "writtenOn": "2023-09-25T14:59:16Z",
      "side": 1,
      "message": "Not sure what was the exact reason for the CI failure, I can\u0027t figure out... Anyway, it passed on re-trigger [1] so I think this was just a glitch.\n\n[1] https://ci.trustedfirmware.org/job/tf-a-ci-gateway/49171/",
      "revId": "616b3ce27d9a8a83a189a16ff6a05698bc6df3c8",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda"
    }
  ]
}