{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "a8ac9450_5bb9f1a9",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1000124
      },
      "writtenOn": "2024-08-13T15:23:44Z",
      "side": 1,
      "message": "Ran in fuzzer and the assertion fail is no longer happening, instead we see error return of SDEI_EDENY.",
      "revId": "7622331aa8e8fdae609318ae6d2f09682bf6d5c8",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda"
    }
  ]
}