{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "761b9cfb_c39a5e6d",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1000102
      },
      "writtenOn": "2022-02-03T10:18:58Z",
      "side": 1,
      "message": "The CI failure seems to be related with this patch, could you please have a look (keeping -1 until confirmed)",
      "revId": "992d97c45faeaee7b6a82089374addcc0dc74344",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda"
    }
  ]
}