{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "55876a2c_b77fa6f6",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 8
      },
      "lineNbr": 0,
      "author": {
        "id": 1000124
      },
      "writtenOn": "2021-08-26T16:09:54Z",
      "side": 1,
      "message": "A lot of false fails and what seems to be network issues with cloning:\n\nERROR: Error cloning remote repo \u0027origin\u0027",
      "revId": "a93bcb6d8209afea0d5376ffc8ec999b9d2b9fce",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda"
    }
  ]
}