{
  "comments": [
    {
      "key": {
        "uuid": "71f21e92_59f60505",
        "filename": "bl31/aarch64/runtime_exceptions.S",
        "patchSetId": 2
      },
      "lineNbr": 95,
      "author": {
        "id": 1000114
      },
      "writtenOn": "2020-11-06T01:17:06Z",
      "side": 1,
      "message": "nit picking here, but there may not be much we can do: If this particular store causes an SError and is taken before CTX_IS_IN_EL3 is set, we will think that the SError came from lower exception level. Is that right ?",
      "range": {
        "startLine": 95,
        "startChar": 1,
        "endLine": 95,
        "endChar": 54
      },
      "revId": "ec4c857bed36cb55434d02da80500d9d6c2c6ebc",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "a6f3c771_c94f05da",
        "filename": "bl31/aarch64/runtime_exceptions.S",
        "patchSetId": 2
      },
      "lineNbr": 148,
      "author": {
        "id": 1000114
      },
      "writtenOn": "2020-11-06T01:17:06Z",
      "side": 1,
      "message": "do we not need to save x19 here? if you get the SError interrupt between str x19(line 132) in handle_async_ea, the original x19 will be clobbered. same with check and unmask ea.. is that not a problem ? maybe i\u0027m missing something..",
      "range": {
        "startLine": 148,
        "startChar": 3,
        "endLine": 148,
        "endChar": 30
      },
      "revId": "ec4c857bed36cb55434d02da80500d9d6c2c6ebc",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda",
      "unresolved": true
    }
  ]
}