{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "63f39853_5f090e8c",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 4
      },
      "lineNbr": 0,
      "author": {
        "id": 1000328
      },
      "writtenOn": "2022-02-10T13:26:18Z",
      "side": 1,
      "message": "Failure CIs passed after re-triggering apart from coverity-scan, but that seems to be known failure. Hence manually giving Verified+1",
      "revId": "f20eb893a072bb9b404eedb886e8c65fe76ffb45",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda"
    }
  ]
}