{
  "comments": [
    {
      "key": {
        "uuid": "c1198e87_a3a708f4",
        "filename": "bl31/aarch64/runtime_exceptions.S",
        "patchSetId": 4
      },
      "lineNbr": 461,
      "author": {
        "id": 1000056
      },
      "writtenOn": "2020-01-22T09:49:30Z",
      "side": 1,
      "message": "Use the `exception_return` macro here.",
      "range": {
        "startLine": 459,
        "startChar": 1,
        "endLine": 461,
        "endChar": 4
      },
      "revId": "ff88bb23260ffdeff7a9f17a179a9e5b2142fca7",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "8f3e4e1c_0bbfa774",
        "filename": "lib/el3_runtime/aarch64/context.S",
        "patchSetId": 4
      },
      "lineNbr": 539,
      "author": {
        "id": 1000056
      },
      "writtenOn": "2020-01-22T09:49:30Z",
      "side": 1,
      "message": "Use the exception_return macro here.",
      "range": {
        "startLine": 537,
        "startChar": 0,
        "endLine": 539,
        "endChar": 4
      },
      "revId": "ff88bb23260ffdeff7a9f17a179a9e5b2142fca7",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda",
      "unresolved": false
    }
  ]
}